// @ts-ignore
import jsonStorageService from "./JsonStorageService.ts";
// @ts-ignore
import type { PasswordReset } from "../types/password_resets.ts";
// @ts-ignore
import jsonStorageServiceUsers from "./JsonStorageService.ts";
// @ts-ignore
import type { User } from "../types/user.types.ts";
// @ts-ignore
import HashService from "./HashService.ts";
// @ts-ignore
import { generateCode } from "../utils/code.ts";

import { fileURLToPath } from "url";
import path from "path";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const passwordResetsPath = path.join(__dirname, "../../database/password_resets.json");
const usersPath = path.join(__dirname, "../../database/users.json");

class PasswordResetService {
    private readonly ttlMs: number = 10 * 60 * 1000;

    /**
     * Creates and stores a reset code generated by the server.
     *
     * @param email - User email.
     * @returns Six-digit reset code that should be sent by email.
     */
    async create(email: string): Promise<string> {
        const code = generateCode();
        await this.createResetCode(email, code);
        return code;
    }

    /**
     * Validates a reset code without throwing to the controller.
     *
     * @param email - User email.
     * @param code - Code received by email.
     * @returns True when the code exists and has not expired.
     */
    async verify(email: string, code: string): Promise<boolean> {
        try {
            await this.verifyCode(email, code);
            return true;
        } catch {
            return false;
        }
    }

    /**
     * Removes all reset codes for the user after successful password change.
     *
     * @param email - User email.
     */
    async consume(email: string): Promise<void> {
        await this.deleteReset(email);
    }

    /**
     * Stores a provided reset code and replaces older codes for this email.
     *
     * @param email - User email.
     * @param code - Six-digit reset code.
     * @returns Persisted reset record with expiration timestamp.
     */
    async createResetCode(email: string, code: string): Promise<PasswordReset> {
        const users: User[] = await jsonStorageServiceUsers.readJSON(usersPath);

        const existingUser: User | undefined = users.find((user: User) => user.email === email);

        if (!existingUser) {
            throw new Error("User with this email does not exist");
        }

        const resets: PasswordReset[] = await jsonStorageService.readJSON(passwordResetsPath) || [];

        const filteredResets: PasswordReset[] = resets.filter((reset: PasswordReset) => reset.email !== email);

        const newReset: PasswordReset = {
            email,
            code,
            expiresAt: Date.now() + this.ttlMs
        };

        filteredResets.push(newReset);

        await jsonStorageService.writeJSON(passwordResetsPath, filteredResets);

        return newReset;
    }

    /**
     * Checks that a reset code exists and has not expired.
     *
     * @param email - User email.
     * @param code - Code received by email.
     * @throws Error when the code is missing or expired.
     */
    async verifyCode(email: string, code: string): Promise<void> {
        const resets: PasswordReset[] = await jsonStorageService.readJSON(passwordResetsPath) || [];

        const reset: PasswordReset | undefined = resets.find((item: PasswordReset) => item.email === email && item.code === code);

        if (!reset) {
            throw new Error("Invalid code");
        }

        if (Date.now() > reset.expiresAt) {
            throw new Error("Code expired");
        }
    }

    /**
     * Updates a user's password and clears used reset codes.
     *
     * @param email - User email.
     * @param newPassword - New raw password.
     * @throws Error when the user does not exist.
     */
    async updatePassword(email: string, newPassword: string): Promise<void> {
        const users: User[] = await jsonStorageServiceUsers.readJSON(usersPath);

        const existingUser: User | undefined = users.find((user: User) => user.email === email);

        if (!existingUser) {
            throw new Error("User with this email does not exist");
        }

        existingUser.hashed_password = await HashService.hashPassword(newPassword);

        await jsonStorageServiceUsers.writeJSON(usersPath, users);

        await this.deleteReset(email);
    }

    /**
     * Deletes all reset codes for a user.
     *
     * @param email - User email.
     */
    private async deleteReset(email: string): Promise<void> {
        const resets: PasswordReset[] = await jsonStorageService.readJSON(passwordResetsPath) || [];

        const filteredResets: PasswordReset[] = resets.filter((item: PasswordReset) => item.email !== email);

        await jsonStorageService.writeJSON(passwordResetsPath, filteredResets);
    }
}

export default new PasswordResetService();
